xdg-generate-desktop: add command-line interface

diff --git a/xdg-generate-desktop b/xdg-generate-desktop
--- a/xdg-generate-desktop
+++ b/xdg-generate-desktop
@@ -1,5 +1,52 @@
 #!/bin/bash
 
+fatal() { [ -n "$1" ] && printf "error: %s\nUse %s --help for usage.\n" "$1" "${0##*/}" >&2; exit 1; }
+usage() {
+cat <<USAGE
+Usage: ${0##*/} [-h] [-d DIR] BASENAME
+
+Generates a .desktop file, .png icon and install script from a given window.
+
+Options:
+  -h|--help     - show this page.
+  -d  DIR       - generate files in DIR instead of current directory.
+                  It will be created if necessary.
+
+  BASENAME      - base name used as a prefix for the generated files.
+                  Usually the executable name.
+
+Window is selected by clicking it with the "+" cursor, just like in xprop.
+
+Install script merely copies the generated BASENAME.desktop and BASENAME.png icon
+to their respective locations uxing xdg-desktop-menu and xdg-icon-resource.
+
+Make sure to edit the generated BASENAME.desktop boilerplate before installing it
+
+Copyright (C) 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
+License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
+USAGE
+}
+
+dir=.
+exec=
+
+# pre-parse help
+for arg in "$@"; do case "$arg" in -h|--help) usage; exit;; esac; done
+
+while [ $# -gt 0 ]; do
+	case "$1" in
+	-d) shift; [ -n "$1" ] || fatal "missing DIR argument for option"; dir="$1";;
+	-*) fatal "invalid option: $1";;
+	*) [ -z "$exec" ] || fatal "too many arguments: $1"; exec="$1";;
+	esac
+	shift
+done
+
+[ -n "$exec" ] || fatal "missing BASENAME argument"
+
+exit
+
+
 xprop -notype 32c _NET_WM_ICON |
 perl -0777 -pe '@_=/\d+/g;
 	printf "P7\nWIDTH %d\nHEIGHT %d\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n", splice@_,0,2;
